def chemical_balancing(pool_type):
  if pool_type == "chlorine":
    print("Free, Combined & Total Chlorine Test:")
    print("1. Rinse and fill small comparator tube to 9mL mark with water to be tested.")
    print("2. Add 5 drops R-0001 and 5 drop R-0002. Cap and invert to mix.")
    print("3. Match color with color standard*. Record as parts per million (ppm) free chlorine.")
    print("4. Add 5 drops R-0003. Cap and invert to mix.")
    print("5. Match color immediately. Record as ppm total chlorine.")
    print("6. Subtract free chlorine (FC) from total chlorine (TC). Record as ppm combined chlorine (CC). Formula: TC - FC = CC.")
    input("Press Enter to continue...")
    print("\npH Test:")
    print("1. Rinse and fill large comparator tube to 44 mL mark with water to be tested.")
    print("2. Add 5 drops R-0004. Cap and invert to mix.")
    print("3. Match color with color standard. Record as pH units and save sample if pH needs adjustment. If sample color is between two values, pH is average of the two. To LOWER pH: See Acid Demand Test. To RAISE pH: See Base Demand Test.")
    input("Press Enter to continue...")
    print("\nAcid Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0005 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nBase Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0006 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nTotal Alkalinity (TA) Test:")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
    print("2. Add 2 drops R-0007. Swirl to mix.")
    print("3. Add 5 drops R-0008. Swirl to mix. Sample will turn green.")
    print("4. Add R-0009 dropwise, swirling and counting after each drop, until color changes from green to red. 5. Multiply drops in step 4 by 10. Record as parts per million (ppm) total alkalinity.")
    print("*When high TA is anticipated: Use 10mL sample, 1 drop R-0007, 3 drops R-0008, and multiply drops in step 4 by 25.")
    input("Press Enter to continue...")
    print("\nCalcium Hardness (CH) Test:")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
    print("2. Add 20 drops R-0010. Swirl to mix.")
    print("3. Add 5 drops R-0011L. Swirl to mix. If calcium hardness is present, sample will turn red.")
    print("4. Add R-0012 dropwise, swirling and counting after each drop, until color changes from red to blue.")
    print("5. Multiply drops in step 4 by 10. Record as ppm calcium chloride.")
	print("6. If color changes from red to blue, subtract number of drops added in step 4 from total number of drops in the tube. This is the calcium hardness (CH). Record as parts per million (ppm). If color does not change to blue, CH is greater than 500 ppm. Record as >500 ppm.")
	print("*When low CH is anticipated: Use 10mL sample, 8 drops R-0010, 2 drops R-0011L, and multiply drops in step 4 by 25.")
	input("Press Enter to continue...")
    print("\nCYA (Cyanuric Acid) Test:")
	print("1. Rinse and fill small comparator tube to 9 mL mark with water to be tested.")
	print("2. Add 3 drops R-0013. Cap and invert to mix.")
	print("3. Add 5 drops R-0014. Cap and invert to mix.")
	print("4. Match color with color standard. Record as parts per million (ppm) CYA.")

  elif pool_type == "bromine":
    print("Bromine Test:")
    print("Total Bromine test: instruct user how to test bromine: 1. Rinse and fill small comparator tube to 9 ml mark with water to be tested.")
    print("2. Add 5 drops R-0001 and 5 drops R-0002. Cap and invert to mix.")
    print("3. Match color with color standard*. Record as parts per million (ppm) total bromine (TB). *If color is off-scale: Repeat test using 4.5 mL sample diluted to 9mL mark with tap water. Multiply reading by 2 to obtain approximate sanitizer level. If color is still off-scale: Repeat test using 1.8mL sample diluted to 9mL mark with tap water. Multiply reading by 5 to obtain approximate sanitizer level.")
    input("Press Enter to continue...")
    print("\npH Test:")
    print("1. Rinse and fill large comparator tube to 44 mL mark with water to be tested.")
    print("2. Add 5 drops R-0004. Cap and invert to mix.")
    print("3. Match color with color standard. Record as pH units and save sample if pH needs adjustment. If sample color is between two values, pH is average of the two. To LOWER pH: See Acid Demand Test. To RAISE pH: See Base Demand Test.")
    input("Press Enter to continue...")
    print("\nAcid Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0005 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nBase Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0006 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nTotal Alkalinity (TA) Test:")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
    print("2. Add 2 drops R-0007. Swirl to mix.")
    print("3. Add 5 drops R-0008. Swirl to mix. Sample will turn green.")
    print("4. Add R-0009 dropwise, swirling to mix.")
	print("5. Multiply drops in step 4 by 10. Record as parts per million (ppm) total alkalinity.")
	print("*When high TA is anticipated: Use 10mL sample, 1 drop R-0007, 3 drops R-0008, and multiply drops in step 4 by 25.")
	print("\nCalcium Hardness (CH) Test:")
	input("Press Enter to continue...")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
	print("2. Add 20 drops R-0010. Swirl to mix.")
	print("3. Add 5 drops R-0011L. Swirl to mix. If calcium hardness is present, sample will turn red.")
	print("4. Add R-0012 dropwise, swirling and counting after each drop, until color changes from red to blue.")
	print("5. Multiply drops in step 4 by 10. Record as parts per million (ppm) calcium hardness.")
	print("6. If color changes from red to blue, subtract number of drops added in step 4 from total number of drops in the tube. This is the calcium hardness (CH). Record as parts per million (ppm). If color does not change to blue, CH is greater than 500 ppm. Record as >500 ppm.")
	print("*When low CH is anticipated: Use 10mL sample, 8 drops R-0010, 2 drops R-0011L, and multiply drops in step 4 by 25.")
	print("\nCYA (Cyanuric Acid) Test:")
	input("Press Enter to continue...")
    print("1. Rinse and fill small comparator tube to 9 mL mark with water to be tested.")
	print("2. Add 3 drops R-0013. Cap and invert to mix.")
	print("3. Add 5 drops R-0014. Cap and invert to mix.")
	print("4. Match color with color standard. Record as parts per million (ppm) CYA.")

  elif pool_type == "salt":
    print("Chlorine Test:")
    print("1. Rinse and fill small comparator tube to 9mL mark with water to be tested.")
    print("2. Add 5 drops R-0001 and 5 drop R-0002. Cap and invert to mix.")
    print("3. Match color with color standard*. Record as parts per million (ppm) free chlorine.")
    print("4. Add 5 drops R-0003. Cap and invert to mix.")
    print("5. Match color immediately. Record as ppm total chlorine.")
    print("6. Subtract free chlorine (FC) from total chlorine (TC). Record as ppm combined chlorine (CC). Formula: TC - FC = CC.")
    input("Press Enter to continue...")
    print("\nSalt Test:")
    print("1. Rinse and fill small comparator tube to 9 mL mark with water to be tested.")
    print("2. Add 5 drops R-0015. Cap and invert to mix.")
    print("3. Add 5 drops R-0016. Cap and invert to mix.")
    print("4. Match color with color standard. Record as parts per thousand (ppt) salt.")
    print("\npH Test:")
    print("1. Rinse and fill large comparator tube to 44 mL mark with water to be tested.")
    print("2. Add 5 drops R-0004. Cap and invert to mix.")
    print("3. Match color with color standard. Record as pH units and save sample if pH needs adjustment. If sample color is between two values, pH is average of the two. To LOWER pH: See Acid Demand Test. To RAISE pH: See Base Demand Test.")
    input("Press Enter to continue...")
    print("\nAcid Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0005 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nBase Demand Test:")
    print("1. Use treated sample from pH test.")
    print("2. Add R-0006 dropwise. After each drop, count, cap and invert to mix, and compare with color standards until desired pH is matched. See Treatment Tables to continue.")
    input("Press Enter to continue...")
    print("\nTotal Alkalinity (TA) Test:")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
    print("2. Add 2 drops R-0007. Swirl to mix.")
    print("3. Add 5 drops R-0008. Swirl to mix. Sample will turn green.")
    print("4. Add R-0009 dropwise, swirling to mix.")
	print("5. Multiply drops in step 4 by 10. Record as parts per million (ppm) total alkalinity.")
	print("*When high TA is anticipated: Use 10mL sample, 1 drop R-0007, 3 drops R-0008, and multiply drops in step 4 by 25.")
	print("\nCalcium Hardness (CH) Test:")
	input("Press Enter to continue...")
    print("1. Rinse and fill large comparator tube to 25 mL mark with water to be tested*.")
	print("2. Add 20 drops R-0010. Swirl to mix.")
	print("3. Add 5 drops R-0011L. Swirl to mix. If calcium hardness is present, sample will turn red.")
	print("4. Add R-0012 dropwise, swirling and counting after each drop, until color changes from red to blue.")
	print("5. Multiply drops in step 4 by 10. Record as parts per million (ppm) calcium hardness.")
	print("6. If color changes from red to blue, subtract number of drops added in step 4 from total number of drops in the tube. This is the calcium hardness (CH). Record as parts per million (ppm). If color does not change to blue, CH is greater than 500 ppm. Record as >500 ppm.")
	print("*When low CH is anticipated: Use 10mL sample, 8 drops R-0010, 2 drops R-0011L, and multiply drops in step 4 by 25.")
	print("\nCYA (Cyanuric Acid) Test:")
	input("Press Enter to continue...")
    print("1. Rinse and fill small comparator tube to 9 mL mark with water to be tested.")
	print("2. Add 3 drops R-0013. Cap and invert to mix.")
	print("3. Add 5 drops R-0014. Cap and invert to mix.")
	print("4. Match color with color standard. Record as parts per million (ppm) CYA.")
  else:
    print("Invalid pool type. Please enter 'chlorine', 'bromine', or 'salt'.")

chemical_balancing("chlorine")
chemical_balancing("bromine")
chemical_balancing("salt")